apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ include "whoami.fullname" . }}-letsencrypt
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ include "whoami.fullname" . }}-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
